package bo.edu.ucbcba.prestamix.group4.view;

import bo.edu.ucbcba.prestamix.group4.controller.FileController;
import bo.edu.ucbcba.prestamix.group4.model.File;
import bo.edu.ucbcba.prestamix.group4.model.Pawn;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.util.List;

public class FilePawn extends JDialog {
    private JPanel rootPanel;
    private JTable fileTable;
    private final FileController fileController;

    public FilePawn(JFrame edit, Pawn p) {
        super(edit, "-ARCHIVADOS-", true);
        setContentPane(rootPanel);
        setSize(500, 600);

        fileController = new FileController();
        save(p);
    }

    public void save(Pawn p) {
        if (p != null) {
            fileController.create(p.getId(), p.getNameCustomer(), p.getCodPledge(),
                    String.valueOf(p.getAmount()), p.getType(), p.getDate(), p.getStatus());
            populateTable();
        }
        else
        {
            populateTable();
        }
    }

    public void populateTable() {
        List<File> files = fileController.show();
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ID");
        model.addColumn("NOMBRE DEL CLIENTE");
        model.addColumn("CODIGO DE LA PRENDA");
        model.addColumn("MONTO");
        model.addColumn("TIPO");
        model.addColumn("FECHA");
        model.addColumn("ESTADO");
        fileTable.setModel(model);

        for (File f : files) {
            Object[] row = new Object[7];

            row[0] = f.getId();
            row[1] = f.getNameCustomer();
            row[2] = f.getCodPledge();
            row[3] = f.getAmount();
            row[4] = f.getType();
            row[5] = f.getDate();
            row[6] = f.getStatus();
            model.addRow(row);
        }
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        rootPanel = new JPanel();
        rootPanel.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        fileTable = new JTable();
        rootPanel.add(fileTable, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(150, 50), null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return rootPanel;
    }
}
